name: brainiac

on: push

jobs:
  first-job:
    runs-on: windows-latest

    steps:
      - name: Print message
        run: echo "Let's dive with brainiac."

      - name: Check Linting
        run: |
          echo "Linting checking..."
          echo "Is there any issue in this code?"
